language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install -e .[test]
  - pip install coveralls
script:
  - pytest --cov ./test/
after_success:
  - coveralls
