name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        name: [
          "ubuntu-py27",
          "ubuntu-py36",
          "ubuntu-py37",
          "ubuntu-py38",
          "ubuntu-py39",
          "macos-py37",
          "macos-py38",
          "macos-py39",
        ]

        include:
          - name: "ubuntu-py27"
            python: "2.7"
            os: ubuntu-latest
          - name: "ubuntu-py36"
            python: "3.6"
            os: ubuntu-latest
          - name: "ubuntu-py37"
            python: "3.7"
            os: ubuntu-latest
          - name: "ubuntu-py38"
            python: "3.8"
            os: ubuntu-latest
          - name: "ubuntu-py39"
            python: "3.9"
            os: ubuntu-latest
          - name: "macos-py37"
            python: "3.7"
            os: macos-latest
          - name: "macos-py38"
            python: "3.8"
            os: macos-latest
          - name: "macos-py39"
            python: "3.9"
            os: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test]
    - name: Test with pytest
      run: |
        pytest
